#ifndef EXT4_USR_CONFIG_H
#define EXT4_USR_CONFIG_H

#define CONFIG_USE_DEFAULT_CFG 1
#define CONFIG_HAVE_OWN_ERRNO 1
#define CONFIG_DEBUG_PRINTF 0
#define CONFIG_DEBUG_ASSERT 0
#define CONFIG_BLOCK_DEV_CACHE_SIZE 128
#define CONFIG_BLOCK_DEV_ENABLE_STATS 0
#define CONFIG_EXT4_BLOCKDEVS_COUNT 4
#define CONFIG_EXT4_MOUNTPOINTS_COUNT 4
#define CONFIG_UNALIGNED_ACCESS 1
#define CONFIG_USE_USER_MALLOC 0

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

#endif
